spring:
    r2dbc:
        url: r2dbc:postgresql://localhost:5432/spring-reactive
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
    flyway:
        url: jdbc:postgresql://localhost:5432/spring-reactive
        user: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}

security:
    secretKey: 722236765770276c3c21344b6a455f3662447d3b4b7b3e2c2b707d7e3e