spring:
    r2dbc:
        url: r2dbc:postgresql://localhost:5432/spring-reactive
        username: sa
        password: password
    flyway:
        url: jdbc:postgresql://localhost:5432/spring-reactive
        user: sa
        password: password
